### ISSUE TITLE
Test if an variable is an Enum.property 

### ISSUE THREAD

**Issue by nevf** [phenax/enum-fp#21]
Given:
````
const Action = Enum([ 'Add', 'Edit', 'Delete', 'DeleteAll', 'Get' ]);
const action = Action.Edit
````
Then somewhere else in the app I want to know if ```action``` is an Enum property or not vs a string or some other type. And I don't have access to ```Action```. 

My tests show ```action``` is typeof ```object```. 

Can you recommend a way to determine is ```action``` is in fact an Enum property.

**Comment by phenax** [comment]
Can you describe the use case where you won't have access to the enum instance?
If you have access to `Action`, you can use the `isConstructor` method to check if a given object is a constructor of the Action enum.

```js
Action.isConstructor(action) === true;
```

**Comment by nevf** [comment]
I pass around Enum properties from module to module. Many of the modules _don't need to know about the Enum instance_ the property belongs to. 

In certain places I need to use the Enum name ie. ```action().name``` for example to persist to a database. 

So I'd like some functions to be able to handle parameters that can be either an enum property or an enum.name. I guess these are 'sum type' properties. ;-) 

In such a function I'll use:
````
const enumName = ( enumOrName ) => is.object( enumOrName ) ? enumOrName().name : enumOrName;
````
to get the `enum.name` from either  a property or name. This works fine, but ```is.object( enumOrName ) ``` isn't very robust. And that's where I'd like to know ```is.enumProperty( xyz )``` without needing to know the Enum instance.

**Comment by phenax** [comment]
@nevf. I feel like you may be using it wrong. The enum constructor needs to be executed and the object needs to be passed around.
Something like, `Action.Add()` instead of `Action.Add`.

And you don't really need to extract the name of an enum. If you are trying something like
```js
if (enumName === 'Add') {
  doSomething();
}
```
you should instead write something like
```js
Action.match(action, {
  Add: () => doSomething(),
  _: () => {},
});
```

Also, just like in any other type system, you need to know what enum type you are using which means, you need access to the enum instance as it is a type definition.

Let me know if this helps.

**Comment by nevf** [comment]
@phenax Ok thanks, I think you are on to something. I'm used to using packages like https://github.com/adrai/enum where you use:
````
if ( enum === Action.Add )
   doSomething()
````
and I'm using ```enum-fp``` the same way.

I'll refactor my code to this _modern fp_ style ;-) and report back.

**Comment by phenax** [comment]
Closing the issue assuming it all worked out well for you
